### ISSUE TITLE
Create tests

### ISSUE THREAD

**Issue by stevermeister** [stevermeister/ng-biscuit#2]

**Comment by icholy** [comment]
You can just steal the `ngCookies` [tests](https://github.com/angular/angular.js/blob/507ee2d9bac77841681282dfcba9297dda576b41/test/ngCookies/cookiesSpec.js#L110-L149).

**Comment by stevermeister** [comment]
good idea!

I was going to do it but Angular team finally fixed cookie module - https://github.com/angular/angular.js/commit/92c366d205da36ec26502aded23db71a6473dad7

so no need in this plugin anymore
