### ISSUE TITLE
cookies are not removed sometimes

### ISSUE THREAD

**Issue by c0debreaker** [stevermeister/ng-biscuit#4]
Hi,

There are times that the cookie is not removed.

The code I'm using is cookieStore.remove("id", { domain : ".mydomain.com" });

Then when I refresh my browser, it will work. I'm using ng-biscuit 0.2.1

Thanks!

**Comment by stevermeister** [comment]
Hi,

it's quite a weird behaviour.
could you create jsfiddle for it?

**Comment by c0debreaker** [comment]
After adding path : '/', it became stable.
